"""Dataset statistics → ``reports/data_stats.md``.

    uv run python -m bhaav.data.stats

Counts per label / source / split, label cardinality, intensity coverage, script mix, CMI buckets
and text length. The report contains numbers only — never dataset text — so it is safe to commit
whatever the source licences say about redistribution.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from collections.abc import Sequence
from pathlib import Path

import numpy as np

from bhaav.data.harmonize import DEDUPE_SUMMARY_NAME, SUMMARY_NAME
from bhaav.data.records import Record, read_jsonl
from bhaav.data.registry import DatasetRegistry, load_registry
from bhaav.paths import ProjectPaths
from bhaav.schema import LabelSchema, load_label_schema

REPORT_NAME = "data_stats.md"
SPLITS = ("train", "val", "test_in_domain", "ood_eval")
#: ``docs/07`` §2.6 buckets, plus an explicit bucket for what falls above them.
CMI_BUCKETS = (
    ("[0, 10)", 0.0, 10.0),
    ("[10, 30)", 10.0, 30.0),
    ("[30, 50]", 30.0, 50.0001),
    ("> 50", 50.0001, 101.0),
)


def _table(header: Sequence[str], rows: Sequence[Sequence[object]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines.extend("| " + " | ".join(str(cell) for cell in row) + " |" for row in rows)
    return lines


def _percent(part: int, whole: int) -> str:
    return f"{part / whole:.1%}" if whole else "–"


def _length_row(name: str, values: Sequence[int]) -> list[object]:
    array = np.asarray(values, dtype=np.float64)
    p50, p95, p99 = (float(np.percentile(array, q)) for q in (50, 95, 99))
    return [name, f"{array.mean():.1f}", f"{p50:.0f}", f"{p95:.0f}", f"{p99:.0f}", int(array.max())]


def render_stats(
    records: Sequence[Record],
    schema: LabelSchema,
    registry: DatasetRegistry,
    harmonize_summary: dict[str, object] | None = None,
    dedupe_summary: dict[str, object] | None = None,
) -> str:
    labels = list(schema.labels)
    sources = sorted({r.source for r in records})
    splits = [s for s in SPLITS if any(r.split == s for r in records)]
    total = len(records)

    lines = [
        "# Data statistics",
        "",
        "Generated by `python -m bhaav.data.stats` from `data/processed/*.jsonl`. "
        "Do not edit by hand.",
        "",
        f"- Records: **{total}** from **{len(sources)}** source(s)",
        f"- Label schema version: {schema.schema_version} · "
        f"mapping version: {registry.mapping_version}",
    ]
    if harmonize_summary:
        lines.append(
            f"- Normalisation version: {harmonize_summary.get('normalization_version')} · "
            f"split seed: {harmonize_summary.get('split_seed')} · "
            f"LID model: {harmonize_summary.get('lid_model') or 'none'}"
        )
    if dedupe_summary:
        lines.append(
            f"- Deduplication: {dedupe_summary.get('removed')} of {dedupe_summary.get('before')} "
            f"records removed (see `reports/dedupe_report.md`)"
        )
    else:
        lines.append("- Deduplication: **not run yet** — these counts may include duplicates")
    if total == 0:
        lines += ["", "No harmonised data yet: no dataset is both `allowed` and has a format spec."]
        return "\n".join(lines) + "\n"

    lines += ["", "## Sources", ""]
    per_source = Counter(r.source for r in records)
    lines += _table(
        ["source", "name", "licence", "records", *splits],
        [
            [
                source,
                registry.datasets[source].name if source in registry.datasets else "–",
                next(r.license for r in records if r.source == source) or "–",
                per_source[source],
                *(sum(1 for r in records if r.source == source and r.split == s) for s in splits),
            ]
            for source in sources
        ],
    )

    lines += ["", "## Label counts by source", "", "A record counts once per active label.", ""]
    lines += _table(
        ["label", *sources, "total", "share of records"],
        [
            [
                label,
                *(
                    sum(1 for r in records if r.source == s and r.labels[label] != 0)
                    for s in sources
                ),
                (n := sum(1 for r in records if r.labels[label] != 0)),
                _percent(n, total),
            ]
            for label in labels
        ],
    )

    lines += ["", "## Label counts by split", ""]
    lines += _table(
        ["label", *splits],
        [
            [
                label,
                *(sum(1 for r in records if r.split == s and r.labels[label] != 0) for s in splits),
            ]
            for label in labels
        ],
    )

    lines += ["", "## Labels per record", ""]
    cardinality = Counter(len(r.active_labels()) for r in records)
    lines += _table(
        ["active labels", "records", "share"],
        [[k, cardinality[k], _percent(cardinality[k], total)] for k in sorted(cardinality)],
    )

    lines += [
        "",
        "## Intensity coverage",
        "",
        "Active emotion labels with a known intensity (1–3) vs unknown "
        "(masked in the intensity loss).",
        "",
    ]
    intensity_rows = []
    for source in sources:
        values = [
            r.labels[e]
            for r in records
            if r.source == source
            for e in schema.emotions
            if r.labels[e] != 0
        ]
        known = sum(1 for v in values if v is not None)
        intensity_rows.append([source, len(values), known, _percent(known, len(values))])
    lines += _table(["source", "active emotion labels", "with intensity", "share"], intensity_rows)

    lines += ["", "## Script", ""]
    scripts = Counter(r.script for r in records)
    lines += _table(
        ["script", "records", "share"],
        [[s, scripts[s], _percent(scripts[s], total)] for s in ("roman", "devanagari", "mixed")],
    )

    lines += ["", "## Code-Mixing Index", ""]
    cmi_values = [r.cmi for r in records if r.cmi is not None]
    if cmi_values:
        lines += _table(
            ["CMI bucket", "records", "share"],
            [
                [
                    name,
                    (n := sum(1 for v in cmi_values if low <= v < high)),
                    _percent(n, len(cmi_values)),
                ]
                for name, low, high in CMI_BUCKETS
            ],
        )
        lines.append("")
        mean_cmi = float(np.mean(cmi_values))
        lines.append(
            f"CMI available for {len(cmi_values)} of {total} records; mean {mean_cmi:.1f}."
        )
    else:
        lines.append(
            "Not available: no trained LID model was present when harmonising (`cmi` is null)."
        )

    lines += ["", "## Text length (normalised text)", ""]
    lines += _table(
        ["unit", "mean", "p50", "p95", "p99", "max"],
        [
            _length_row("characters", [len(r.text_norm) for r in records]),
            _length_row("whitespace tokens", [len(r.text_norm.split(" ")) for r in records]),
        ],
    )

    flags = Counter(flag for r in records for flag in r.flags)
    shouting = sum(r.has_caps_shouting for r in records)
    lines += ["", "## Flags", ""]
    lines += _table(
        ["flag", "records"],
        [*([flag, n] for flag, n in sorted(flags.items())), ["has_caps_shouting", shouting]],
    )
    return "\n".join(lines) + "\n"


def _read_summary(path: Path) -> dict[str, object] | None:
    if not path.is_file():
        return None
    loaded: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return loaded


def run(paths: ProjectPaths) -> Path:
    schema = load_label_schema(paths.label_schema)
    registry = load_registry(paths.datasets, schema)
    records = [r for f in sorted(paths.processed.glob("*.jsonl")) for r in read_jsonl(f)]
    report = render_stats(
        records,
        schema,
        registry,
        _read_summary(paths.processed / SUMMARY_NAME),
        _read_summary(paths.processed / DEDUPE_SUMMARY_NAME),
    )
    paths.reports.mkdir(parents=True, exist_ok=True)
    out = paths.reports / REPORT_NAME
    out.write_bytes(report.encode("utf-8"))
    return out


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="bhaav.data.stats", description=__doc__.split("\n")[0])
    parser.parse_args(argv)
    paths = ProjectPaths.discover()
    out = run(paths)
    print(f"wrote {out.relative_to(paths.root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
